#**Pandas**

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Data mining & ML/weather_data.csv")

In [4]:
df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        7.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [ ]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     32.833333   7.000000
std       4.020779   3.224903
min      28.000000   2.000000
25%      31.250000   6.250000
50%      32.000000   7.000000
75%      33.500000   7.750000
max      40.000000  12.000000

In [ ]:
df.head(3)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/4/2017          NaN        7.0  Sunny
2  1/5/2017         28.0        NaN   Snow

In [ ]:
df.tail(3)

         day  temperature  windspeed   event
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [ ]:
df.dtypes

day             object
temperature    float64
windspeed      float64
event           object
dtype: object

In [ ]:
df.shape

(9, 4)

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df['event']

0      Rain
1     Sunny
2      Snow
3       NaN
4      Rain
5     Sunny
6       NaN
7    Cloudy
8     Sunny
Name: event, dtype: object

In [ ]:
df['event'].value_counts()

Sunny     3
Rain      2
Snow      1
Cloudy    1
Name: event, dtype: int64

In [ ]:
df.groupby('event').get_group('Sunny')

         day  temperature  windspeed  event
1   1/4/2017          NaN        7.0  Sunny
5   1/8/2017         31.0        2.0  Sunny
8  1/11/2017         40.0       12.0  Sunny

In [ ]:
df.isnull()

     day  temperature  windspeed  event
0  False        False      False  False
1  False         True      False  False
2  False        False       True  False
3  False         True      False   True
4  False        False       True  False
5  False        False      False  False
6  False         True       True   True
7  False        False      False  False
8  False        False      False  False

In [ ]:
df.isnull().sum()

day            0
temperature    3
windspeed      3
event          2
dtype: int64

In [ ]:
df['temperature'].isnull()==True

0    False
1     True
2    False
3     True
4    False
5    False
6     True
7    False
8    False
Name: temperature, dtype: bool

In [ ]:
new_df = df.fillna(0)
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          0.0        7.0   Sunny
2   1/5/2017         28.0        0.0    Snow
3   1/6/2017          0.0        7.0       0
4   1/7/2017         32.0        0.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017          0.0        0.0       0
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [ ]:

new_df = df.fillna({
        'temperature': 33.0,
        'windspeed': 5.0,
        'event': 'No Event'
    })
new_df

         day  temperature  windspeed     event
0   1/1/2017         32.0        6.0      Rain
1   1/4/2017         33.0        7.0     Sunny
2   1/5/2017         28.0        5.0      Snow
3   1/6/2017         33.0        7.0  No Event
4   1/7/2017         32.0        5.0      Rain
5   1/8/2017         31.0        2.0     Sunny
6   1/9/2017         33.0        5.0  No Event
7  1/10/2017         34.0        8.0    Cloudy
8  1/11/2017         40.0       12.0     Sunny

In [ ]:
new_df = df.fillna(method="ffill")
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         32.0        7.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         28.0        7.0    Snow
4   1/7/2017         32.0        7.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017         31.0        2.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [ ]:
new_df = df.fillna(method="bfill")
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017         28.0        7.0   Sunny
2   1/5/2017         28.0        7.0    Snow
3   1/6/2017         32.0        7.0    Rain
4   1/7/2017         32.0        2.0    Rain
5   1/8/2017         31.0        2.0   Sunny
6   1/9/2017         34.0        8.0  Cloudy
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [ ]:
new_df = df.dropna()
new_df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
5   1/8/2017         31.0        2.0   Sunny
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny