In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
from sklearn import tree
import pydotplus
from sklearn.model_selection import train_test_split

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

In [4]:
df=pd.read_csv('/content/drive/MyDrive/Data mining & ML/heart_failure.csv')
df

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

Check Null Value

In [5]:
df.isnull().values.any()

False

In [6]:
df.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

Seperate Feature Columns

In [7]:
x = df.drop(['DEATH_EVENT'], axis = 1)
x

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8
...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285

Seperate Class Column

In [8]:
y = df['DEATH_EVENT']
y

0      1
1      1
2      1
3      1
4      1
      ..
294    0
295    0
296    0
297    0
298    0
Name: DEATH_EVENT, Length: 299, dtype: int64

In [9]:
dummy_y = np_utils.to_categorical(y)

In [10]:
dummy_y.shape

(299, 2)

Train, Test & Split our dataset into 70:30

In [11]:
xtrain,xtest,ytrain,ytest= train_test_split(x,dummy_y,test_size=.3,random_state=1)

Create an ANN model with Kears,
Fit our Train dtata into our model

In [18]:
model = Sequential()
model.add(Dense(12, input_shape=(12,), activation='relu')) #input_shape 12 because there are 12 features in x
model.add(Dense(8, activation='relu'))
model.add(Dense(2, activation='sigmoid')) #output is 2 because we classify 2 types of classes

In [19]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [20]:
model.fit(xtrain, ytrain, batch_size = 5, epochs = 200)

Epoch 1/200
42/42 [==============================] - 1s 2ms/step - loss: 14223.3369 - accuracy: 0.6651
Epoch 2/200
42/42 [==============================] - 0s 2ms/step - loss: 5113.8809 - accuracy: 0.6651
Epoch 3/200
42/42 [==============================] - 0s 2ms/step - loss: 510.6562 - accuracy: 0.5694
Epoch 4/200
42/42 [==============================] - 0s 2ms/step - loss: 128.2889 - accuracy: 0.5598
Epoch 5/200
42/42 [==============================] - 0s 2ms/step - loss: 91.9368 - accuracy: 0.6268
Epoch 6/200
42/42 [==============================] - 0s 2ms/step - loss: 83.4251 - accuracy: 0.6029
Epoch 7/200
42/42 [==============================] - 0s 2ms/step - loss: 77.2796 - accuracy: 0.5598
Epoch 8/200
42/42 [==============================] - 0s 2ms/step - loss: 114.4603 - accuracy: 0.5455
Epoch 9/200
42/42 [==============================] - 0s 2ms/step - loss: 119.1508 - accuracy: 0.6077
Epoch 10/200
42/42 [==============================] - 0s 2ms/step - loss: 107.6308 - accuracy: 0.5359
Epoch 11/200
42/42 [==============================] - 0s 2ms/step - loss: 81.9449 - accuracy: 0.6124
Epoch 12/200
42/42 [==============================] - 0s 2ms/step - loss: 93.6170 - accuracy: 0.5837
Epoch 13/200
42/42 [==============================] - 0s 2ms/step - loss: 136.1477 - accuracy: 0.6029
Epoch 14/200
42/42 [==============================] - 0s 2ms/step - loss: 102.1800 - accuracy: 0.5885
Epoch 15/200
42/42 [==============================] - 0s 2ms/step - loss: 64.2780 - accuracy: 0.6172
Epoch 16/200
42/42 [==============================] - 0s 2ms/step - loss: 73.5559 - accuracy: 0.5550
Epoch 17/200
42/42 [==============================] - 0s 2ms/step - loss: 78.8566 - accuracy: 0.6220
Epoch 18/200
42/42 [==============================] - 0s 2ms/step - loss: 74.3456 - accuracy: 0.5502
Epoch 19/200
42/42 [==============================] - 0s 2ms/step - loss: 71.7745 - accuracy: 0.5455
Epoch 20/200
42/42 [==============================] - 0s 2ms/step - loss: 120.2709 - accuracy: 0.6077
Epoch 21/200
42/42 [==============================] - 0s 2ms/step - loss: 80.5677 - accuracy: 0.5598
Epoch 22/200
42/42 [==============================] - 0s 2ms/step - loss: 76.2869 - accuracy: 0.6124
Epoch 23/200
42/42 [==============================] - 0s 2ms/step - loss: 45.1486 - accuracy: 0.6459
Epoch 24/200
42/42 [==============================] - 0s 2ms/step - loss: 69.0133 - accuracy: 0.6172
Epoch 25/200
42/42 [==============================] - 0s 2ms/step - loss: 94.5849 - accuracy: 0.5837
Epoch 26/200
42/42 [==============================] - 0s 5ms/step - loss: 53.9173 - accuracy: 0.5646
Epoch 27/200
42/42 [==============================] - 0s 11ms/step - loss: 90.2066 - accuracy: 0.5885
Epoch 28/200
42/42 [==============================] - 0s 2ms/step - loss: 91.6368 - accuracy: 0.5359
Epoch 29/200
42/42 [==============================] - 0s 2ms/step - loss: 61.6255 - accuracy: 0.6124
Epoch 30/200
42/42 [==============================] - 0s 2ms/step - loss: 65.1727 - accuracy: 0.5502
Epoch 31/200
42/42 [==============================] - 0s 2ms/step - loss: 65.5767 - accuracy: 0.6124
Epoch 32/200
42/42 [==============================] - 0s 2ms/step - loss: 58.4563 - accuracy: 0.6077
Epoch 33/200
42/42 [==============================] - 0s 3ms/step - loss: 91.7916 - accuracy: 0.5455
Epoch 34/200
42/42 [==============================] - 0s 5ms/step - loss: 83.0899 - accuracy: 0.5885
Epoch 35/200
42/42 [==============================] - 0s 5ms/step - loss: 46.5565 - accuracy: 0.5885
Epoch 36/200
42/42 [==============================] - 0s 2ms/step - loss: 50.9676 - accuracy: 0.6699
Epoch 37/200
42/42 [==============================] - 0s 2ms/step - loss: 67.4932 - accuracy: 0.5789
Epoch 38/200
42/42 [==============================] - 0s 2ms/step - loss: 72.2389 - accuracy: 0.6077
Epoch 39/200
42/42 [==============================] - 0s 2ms/step - loss: 94.2473 - accuracy: 0.5981
Epoch 40/200
42/42 [==============================] - 0s 2ms/step - loss: 74.3093 - accuracy: 0.6029
Epoch 41/200
42/42 [==============================] - 0s 2ms/step - loss: 84.3843 - accuracy: 0.5837
Epoch 42/200
42/42 [==============================] - 0s 2ms/step - loss: 112.0655 - accuracy: 0.6124
Epoch 43/200
42/42 [==============================] - 0s 2ms/step - loss: 55.4231 - accuracy: 0.5694
Epoch 44/200
42/42 [==============================] - 0s 2ms/step - loss: 49.9240 - accuracy: 0.5694
Epoch 45/200
42/42 [==============================] - 0s 2ms/step - loss: 77.8974 - accuracy: 0.5455
Epoch 46/200
42/42 [==============================] - 0s 2ms/step - loss: 81.2768 - accuracy: 0.6124
Epoch 47/200
42/42 [==============================] - 0s 2ms/step - loss: 99.9124 - accuracy: 0.5837
Epoch 48/200
42/42 [==============================] - 0s 2ms/step - loss: 36.6236 - accuracy: 0.6077
Epoch 49/200
42/42 [==============================] - 0s 2ms/step - loss: 67.3191 - accuracy: 0.5215
Epoch 50/200
42/42 [==============================] - 0s 2ms/step - loss: 70.6328 - accuracy: 0.5789
Epoch 51/200
42/42 [==============================] - 0s 2ms/step - loss: 85.9103 - accuracy: 0.5646
Epoch 52/200
42/42 [==============================] - 0s 2ms/step - loss: 59.4271 - accuracy: 0.6029
Epoch 53/200
42/42 [==============================] - 0s 2ms/step - loss: 73.2201 - accuracy: 0.6124
Epoch 54/200
42/42 [==============================] - 0s 2ms/step - loss: 59.6411 - accuracy: 0.6268
Epoch 55/200
42/42 [==============================] - 0s 2ms/step - loss: 91.0657 - accuracy: 0.6029
Epoch 56/200
42/42 [==============================] - 0s 2ms/step - loss: 94.6803 - accuracy: 0.5598
Epoch 57/200
42/42 [==============================] - 0s 2ms/step - loss: 27.3006 - accuracy: 0.6938
Epoch 58/200
42/42 [==============================] - 0s 2ms/step - loss: 54.8164 - accuracy: 0.6220
Epoch 59/200
42/42 [==============================] - 0s 2ms/step - loss: 67.0678 - accuracy: 0.6029
Epoch 60/200
42/42 [==============================] - 0s 2ms/step - loss: 107.1158 - accuracy: 0.5789
Epoch 61/200
42/42 [==============================] - 0s 2ms/step - loss: 85.7557 - accuracy: 0.6268
Epoch 62/200
42/42 [==============================] - 0s 2ms/step - loss: 52.6349 - accuracy: 0.6746
Epoch 63/200
42/42 [==============================] - 0s 2ms/step - loss: 86.6853 - accuracy: 0.6172
Epoch 64/200
42/42 [==============================] - 0s 2ms/step - loss: 41.0705 - accuracy: 0.6746
Epoch 65/200
42/42 [==============================] - 0s 2ms/step - loss: 77.5096 - accuracy: 0.5789
Epoch 66/200
42/42 [==============================] - 0s 2ms/step - loss: 29.9037 - accuracy: 0.6411
Epoch 67/200
42/42 [==============================] - 0s 2ms/step - loss: 49.3952 - accuracy: 0.6507
Epoch 68/200
42/42 [==============================] - 0s 2ms/step - loss: 78.7457 - accuracy: 0.5598
Epoch 69/200
42/42 [==============================] - 0s 2ms/step - loss: 111.7098 - accuracy: 0.5885
Epoch 70/200
42/42 [==============================] - 0s 2ms/step - loss: 52.0877 - accuracy: 0.6172
Epoch 71/200
42/42 [==============================] - 0s 2ms/step - loss: 66.0291 - accuracy: 0.6029
Epoch 72/200
42/42 [==============================] - 0s 2ms/step - loss: 58.1930 - accuracy: 0.5933
Epoch 73/200
42/42 [==============================] - 0s 2ms/step - loss: 45.5190 - accuracy: 0.6459
Epoch 74/200
42/42 [==============================] - 0s 2ms/step - loss: 41.2311 - accuracy: 0.5981
Epoch 75/200
42/42 [==============================] - 0s 2ms/step - loss: 62.0494 - accuracy: 0.6220
Epoch 76/200
42/42 [==============================] - 0s 5ms/step - loss: 50.8725 - accuracy: 0.6124
Epoch 77/200
42/42 [==============================] - 0s 4ms/step - loss: 67.4220 - accuracy: 0.6172
Epoch 78/200
42/42 [==============================] - 0s 3ms/step - loss: 32.7279 - accuracy: 0.6890
Epoch 79/200
42/42 [==============================] - 0s 4ms/step - loss: 41.8206 - accuracy: 0.6699
Epoch 80/200
42/42 [==============================] - 0s 2ms/step - loss: 96.7607 - accuracy: 0.6077
Epoch 81/200
42/42 [==============================] - 0s 2ms/step - loss: 51.3329 - accuracy: 0.6077
Epoch 82/200
42/42 [==============================] - 0s 2ms/step - loss: 75.7877 - accuracy: 0.6603
Epoch 83/200
42/42 [==============================] - 0s 2ms/step - loss: 45.8812 - accuracy: 0.6603
Epoch 84/200
42/42 [==============================] - 0s 3ms/step - loss: 93.1365 - accuracy: 0.6077
Epoch 85/200
42/42 [==============================] - 0s 2ms/step - loss: 29.8270 - accuracy: 0.7081
Epoch 86/200
42/42 [==============================] - 0s 4ms/step - loss: 42.6009 - accuracy: 0.6986
Epoch 87/200
42/42 [==============================] - 0s 3ms/step - loss: 57.6885 - accuracy: 0.5933
Epoch 88/200
42/42 [==============================] - 0s 2ms/step - loss: 91.5302 - accuracy: 0.5407
Epoch 89/200
42/42 [==============================] - 0s 3ms/step - loss: 47.1685 - accuracy: 0.6459
Epoch 90/200
42/42 [==============================] - 0s 4ms/step - loss: 87.0560 - accuracy: 0.6077
Epoch 91/200
42/42 [==============================] - 0s 6ms/step - loss: 100.1818 - accuracy: 0.6029
Epoch 92/200
42/42 [==============================] - 0s 7ms/step - loss: 71.0084 - accuracy: 0.6651
Epoch 93/200
42/42 [==============================] - 0s 2ms/step - loss: 103.7575 - accuracy: 0.5885
Epoch 94/200
42/42 [==============================] - 0s 2ms/step - loss: 38.4691 - accuracy: 0.6220
Epoch 95/200
42/42 [==============================] - 0s 2ms/step - loss: 47.8386 - accuracy: 0.6555
Epoch 96/200
42/42 [==============================] - 0s 3ms/step - loss: 54.2490 - accuracy: 0.6459
Epoch 97/200
42/42 [==============================] - 0s 2ms/step - loss: 51.5126 - accuracy: 0.6268
Epoch 98/200
42/42 [==============================] - 0s 2ms/step - loss: 87.8371 - accuracy: 0.5933
Epoch 99/200
42/42 [==============================] - 0s 2ms/step - loss: 112.4397 - accuracy: 0.5598
Epoch 100/200
42/42 [==============================] - 0s 5ms/step - loss: 63.1434 - accuracy: 0.5598
Epoch 101/200
42/42 [==============================] - 0s 3ms/step - loss: 29.7525 - accuracy: 0.6603
Epoch 102/200
42/42 [==============================] - 0s 2ms/step - loss: 32.4167 - accuracy: 0.6842
Epoch 103/200
42/42 [==============================] - 0s 2ms/step - loss: 59.5792 - accuracy: 0.6220
Epoch 104/200
42/42 [==============================] - 0s 2ms/step - loss: 31.8262 - accuracy: 0.6364
Epoch 105/200
42/42 [==============================] - 0s 2ms/step - loss: 46.0445 - accuracy: 0.6603
Epoch 106/200
42/42 [==============================] - 0s 2ms/step - loss: 54.4937 - accuracy: 0.6316
Epoch 107/200
42/42 [==============================] - 0s 2ms/step - loss: 70.0812 - accuracy: 0.6459
Epoch 108/200
42/42 [==============================] - 0s 3ms/step - loss: 85.6102 - accuracy: 0.5837
Epoch 109/200
42/42 [==============================] - 0s 5ms/step - loss: 46.1011 - accuracy: 0.6459
Epoch 110/200
42/42 [==============================] - 0s 2ms/step - loss: 56.7801 - accuracy: 0.6268
Epoch 111/200
42/42 [==============================] - 0s 5ms/step - loss: 105.4337 - accuracy: 0.6029
Epoch 112/200
42/42 [==============================] - 0s 4ms/step - loss: 46.9067 - accuracy: 0.6172
Epoch 113/200
42/42 [==============================] - 0s 3ms/step - loss: 44.9359 - accuracy: 0.6651
Epoch 114/200
42/42 [==============================] - 0s 3ms/step - loss: 56.6866 - accuracy: 0.6124
Epoch 115/200
42/42 [==============================] - 0s 3ms/step - loss: 74.0902 - accuracy: 0.5981
Epoch 116/200
42/42 [==============================] - 0s 3ms/step - loss: 90.0217 - accuracy: 0.6172
Epoch 117/200
42/42 [==============================] - 0s 3ms/step - loss: 77.1222 - accuracy: 0.6124
Epoch 118/200
42/42 [==============================] - 0s 3ms/step - loss: 95.7490 - accuracy: 0.6077
Epoch 119/200
42/42 [==============================] - 0s 2ms/step - loss: 68.7303 - accuracy: 0.6172
Epoch 120/200
42/42 [==============================] - 0s 2ms/step - loss: 75.1317 - accuracy: 0.6220
Epoch 121/200
42/42 [==============================] - 0s 2ms/step - loss: 73.8163 - accuracy: 0.6124
Epoch 122/200
42/42 [==============================] - 0s 2ms/step - loss: 65.2496 - accuracy: 0.6316
Epoch 123/200
42/42 [==============================] - 0s 2ms/step - loss: 53.8885 - accuracy: 0.6268
Epoch 124/200
42/42 [==============================] - 0s 2ms/step - loss: 59.5224 - accuracy: 0.5646
Epoch 125/200
42/42 [==============================] - 0s 2ms/step - loss: 32.4618 - accuracy: 0.6651
Epoch 126/200
42/42 [==============================] - 0s 4ms/step - loss: 64.5189 - accuracy: 0.6124
Epoch 127/200
42/42 [==============================] - 0s 3ms/step - loss: 91.3434 - accuracy: 0.6603
Epoch 128/200
42/42 [==============================] - 0s 3ms/step - loss: 44.8068 - accuracy: 0.6220
Epoch 129/200
42/42 [==============================] - 0s 2ms/step - loss: 51.3522 - accuracy: 0.6364
Epoch 130/200
42/42 [==============================] - 0s 2ms/step - loss: 50.8115 - accuracy: 0.6172
Epoch 131/200
42/42 [==============================] - 0s 3ms/step - loss: 49.9300 - accuracy: 0.6316
Epoch 132/200
42/42 [==============================] - 0s 5ms/step - loss: 45.2651 - accuracy: 0.6172
Epoch 133/200
42/42 [==============================] - 0s 4ms/step - loss: 45.7489 - accuracy: 0.6411
Epoch 134/200
42/42 [==============================] - 0s 3ms/step - loss: 52.9679 - accuracy: 0.6268
Epoch 135/200
42/42 [==============================] - 0s 2ms/step - loss: 72.8415 - accuracy: 0.6268
Epoch 136/200
42/42 [==============================] - 0s 2ms/step - loss: 41.3234 - accuracy: 0.6555
Epoch 137/200
42/42 [==============================] - 0s 2ms/step - loss: 39.5859 - accuracy: 0.5981
Epoch 138/200
42/42 [==============================] - 0s 2ms/step - loss: 64.6510 - accuracy: 0.6077
Epoch 139/200
42/42 [==============================] - 0s 2ms/step - loss: 47.6085 - accuracy: 0.6555
Epoch 140/200
42/42 [==============================] - 0s 2ms/step - loss: 77.8272 - accuracy: 0.6603
Epoch 141/200
42/42 [==============================] - 0s 3ms/step - loss: 64.2189 - accuracy: 0.5981
Epoch 142/200
42/42 [==============================] - 0s 2ms/step - loss: 35.2685 - accuracy: 0.6699
Epoch 143/200
42/42 [==============================] - 0s 2ms/step - loss: 30.5763 - accuracy: 0.6746
Epoch 144/200
42/42 [==============================] - 0s 2ms/step - loss: 92.1651 - accuracy: 0.5981
Epoch 145/200
42/42 [==============================] - 0s 4ms/step - loss: 108.5886 - accuracy: 0.6220
Epoch 146/200
42/42 [==============================] - 0s 2ms/step - loss: 47.7826 - accuracy: 0.7129
Epoch 147/200
42/42 [==============================] - 0s 2ms/step - loss: 40.4896 - accuracy: 0.6555
Epoch 148/200
42/42 [==============================] - 0s 2ms/step - loss: 45.0091 - accuracy: 0.6507
Epoch 149/200
42/42 [==============================] - 0s 2ms/step - loss: 46.5970 - accuracy: 0.6364
Epoch 150/200
42/42 [==============================] - 0s 3ms/step - loss: 42.7972 - accuracy: 0.6603
Epoch 151/200
42/42 [==============================] - 0s 2ms/step - loss: 61.8950 - accuracy: 0.6268
Epoch 152/200
42/42 [==============================] - 0s 2ms/step - loss: 43.6294 - accuracy: 0.6364
Epoch 153/200
42/42 [==============================] - 0s 2ms/step - loss: 55.0163 - accuracy: 0.6220
Epoch 154/200
42/42 [==============================] - 0s 2ms/step - loss: 43.6217 - accuracy: 0.6411
Epoch 155/200
42/42 [==============================] - 0s 3ms/step - loss: 66.6708 - accuracy: 0.6364
Epoch 156/200
42/42 [==============================] - 0s 3ms/step - loss: 64.7316 - accuracy: 0.6124
Epoch 157/200
42/42 [==============================] - 0s 4ms/step - loss: 48.1786 - accuracy: 0.6555
Epoch 158/200
42/42 [==============================] - 0s 2ms/step - loss: 64.5634 - accuracy: 0.6077
Epoch 159/200
42/42 [==============================] - 0s 2ms/step - loss: 40.7828 - accuracy: 0.6411
Epoch 160/200
42/42 [==============================] - 0s 4ms/step - loss: 36.2117 - accuracy: 0.6938
Epoch 161/200
42/42 [==============================] - 0s 3ms/step - loss: 30.2410 - accuracy: 0.6603
Epoch 162/200
42/42 [==============================] - 0s 2ms/step - loss: 83.2479 - accuracy: 0.5550
Epoch 163/200
42/42 [==============================] - 0s 2ms/step - loss: 93.1822 - accuracy: 0.6077
Epoch 164/200
42/42 [==============================] - 0s 2ms/step - loss: 52.3421 - accuracy: 0.6746
Epoch 165/200
42/42 [==============================] - 0s 2ms/step - loss: 40.9909 - accuracy: 0.6507
Epoch 166/200
42/42 [==============================] - 0s 2ms/step - loss: 54.2713 - accuracy: 0.6699
Epoch 167/200
42/42 [==============================] - 0s 2ms/step - loss: 45.5850 - accuracy: 0.7033
Epoch 168/200
42/42 [==============================] - 0s 2ms/step - loss: 51.7552 - accuracy: 0.6555
Epoch 169/200
42/42 [==============================] - 0s 2ms/step - loss: 51.2471 - accuracy: 0.6172
Epoch 170/200
42/42 [==============================] - 0s 4ms/step - loss: 52.2869 - accuracy: 0.6651
Epoch 171/200
42/42 [==============================] - 0s 2ms/step - loss: 52.1474 - accuracy: 0.6603
Epoch 172/200
42/42 [==============================] - 0s 2ms/step - loss: 71.1276 - accuracy: 0.5981
Epoch 173/200
42/42 [==============================] - 0s 2ms/step - loss: 104.4505 - accuracy: 0.6364
Epoch 174/200
42/42 [==============================] - 0s 4ms/step - loss: 38.9240 - accuracy: 0.6699
Epoch 175/200
42/42 [==============================] - 0s 3ms/step - loss: 52.4514 - accuracy: 0.6172
Epoch 176/200
42/42 [==============================] - 0s 3ms/step - loss: 20.2543 - accuracy: 0.7321
Epoch 177/200
42/42 [==============================] - 0s 3ms/step - loss: 55.5881 - accuracy: 0.6603
Epoch 178/200
42/42 [==============================] - 0s 2ms/step - loss: 75.8516 - accuracy: 0.5837
Epoch 179/200
42/42 [==============================] - 0s 2ms/step - loss: 22.4999 - accuracy: 0.7177
Epoch 180/200
42/42 [==============================] - 0s 3ms/step - loss: 21.0616 - accuracy: 0.6986
Epoch 181/200
42/42 [==============================] - 0s 4ms/step - loss: 33.9394 - accuracy: 0.6555
Epoch 182/200
42/42 [==============================] - 0s 2ms/step - loss: 31.7489 - accuracy: 0.7177
Epoch 183/200
42/42 [==============================] - 0s 2ms/step - loss: 49.0381 - accuracy: 0.7416
Epoch 184/200
42/42 [==============================] - 0s 3ms/step - loss: 51.3276 - accuracy: 0.6507
Epoch 185/200
42/42 [==============================] - 0s 2ms/step - loss: 26.0836 - accuracy: 0.6842
Epoch 186/200
42/42 [==============================] - 0s 2ms/step - loss: 40.4281 - accuracy: 0.6938
Epoch 187/200
42/42 [==============================] - 0s 2ms/step - loss: 62.6381 - accuracy: 0.6172
Epoch 188/200
42/42 [==============================] - 0s 3ms/step - loss: 56.4574 - accuracy: 0.6268
Epoch 189/200
42/42 [==============================] - 0s 3ms/step - loss: 25.7880 - accuracy: 0.6794
Epoch 190/200
42/42 [==============================] - 0s 4ms/step - loss: 39.3048 - accuracy: 0.6794
Epoch 191/200
42/42 [==============================] - 0s 2ms/step - loss: 37.2450 - accuracy: 0.6603
Epoch 192/200
42/42 [==============================] - 0s 3ms/step - loss: 22.7068 - accuracy: 0.6986
Epoch 193/200
42/42 [==============================] - 0s 2ms/step - loss: 53.2129 - accuracy: 0.6459
Epoch 194/200
42/42 [==============================] - 0s 2ms/step - loss: 92.9353 - accuracy: 0.6077
Epoch 195/200
42/42 [==============================] - 0s 3ms/step - loss: 96.0689 - accuracy: 0.5885
Epoch 196/200
42/42 [==============================] - 0s 2ms/step - loss: 162.1730 - accuracy: 0.5837
Epoch 197/200

In [24]:
_, accuracy = model.evaluate(xtest, ytest)
print('Accuracy: %.2f' % (accuracy*100))

3/3 [==============================] - 0s 4ms/step - loss: 28.8003 - accuracy: 0.8222
Accuracy: 82.22

In [25]:
y_pred = model.predict(xtest)
y_pred=np.argmax(y_pred, axis=1)

In [26]:
y_acctual=np.argmax(ytest, axis=1)

In [28]:
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_acctual, y_pred)
print(cm)

[[61  3]
 [14 12]]

In [29]:
print(classification_report(y_acctual, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.95      0.88        64
           1       0.80      0.46      0.59        26

    accuracy                           0.81        90
   macro avg       0.81      0.71      0.73        90
weighted avg       0.81      0.81      0.79        90